export interface ResponsesRequest {
  model: string;
  input: unknown;
  instructions?: string;
  temperature?: number;
  max_output_tokens?: number;
  tools?: unknown;
  tool_choice?: unknown;
  stream?: boolean;
}

export function responsesToChat(request: ResponsesRequest) {
  const messages: Array<any> = [];

  if (request.instructions) {
    messages.push({ role: "system", content: request.instructions });
  }

  if (typeof request.input === "string") {
    messages.push({ role: "user", content: request.input });
  } else if (Array.isArray(request.input)) {
    for (const item of request.input) {
      if (typeof item !== "object" || item === null) continue;

      const value = item as any;

      // 1. Function Call Output from tool execution
      if (value.type === "function_call_output" || value.role === "tool") {
        messages.push({
          role: "tool",
          tool_call_id: value.call_id || value.id || "call_default",
          content: typeof value.output === "string" ? value.output : JSON.stringify(value.output ?? "")
        });
        continue;
      }

      // 2. Function Call generated by assistant
      if (value.type === "function_call") {
        messages.push({
          role: "assistant",
          content: null,
          tool_calls: [
            {
              id: value.call_id || value.id || `call_${crypto.randomUUID()}`,
              type: "function",
              function: {
                name: value.name || "",
                arguments: typeof value.arguments === "string" ? value.arguments : JSON.stringify(value.arguments ?? {})
              }
            }
          ]
        });
        continue;
      }

      // 3. Regular chat message
      let role: "system" | "user" | "assistant" = "user";
      if (value.role === "developer" || value.role === "system") role = "system";
      else if (value.role === "assistant") role = "assistant";
      else if (value.role === "user") role = "user";

      let content = "";
      if (typeof value.content === "string") {
        content = value.content;
      } else if (Array.isArray(value.content)) {
        const parts: string[] = [];
        for (const part of value.content) {
          if (typeof part !== "object" || part === null) continue;
          if (typeof part.text === "string") parts.push(part.text);
          else if (part.type === "input_text" && typeof part.text === "string") parts.push(part.text);
          else if (part.type === "output_text" && typeof part.text === "string") parts.push(part.text);
        }
        content = parts.join("");
      }

      messages.push({ role, content });
    }
  }

  // Normalize tools to standard Chat Completions format
  let tools: any = undefined;
  if (Array.isArray(request.tools)) {
    tools = request.tools.map((t: any) => {
      if (typeof t !== "object" || t === null) return t;
      if (t.type === "function" && !t.function && t.name) {
        return {
          type: "function",
          function: {
            name: t.name,
            description: t.description || "",
            parameters: t.parameters || { type: "object", properties: {} }
          }
        };
      }
      return t;
    });
  }

  return {
    model: request.model,
    messages,
    ...(tools !== undefined ? { tools } : {}),
    ...(request.tool_choice !== undefined ? { tool_choice: request.tool_choice } : {}),
    ...(request.temperature !== undefined ? { temperature: request.temperature } : {}),
    ...(request.max_output_tokens !== undefined ? { max_tokens: request.max_output_tokens } : {}),
    ...(request.stream !== undefined ? { stream: request.stream } : {})
  };
}

export function chatToResponses(chatResponse: any) {
  const responseId = chatResponse?.id ?? crypto.randomUUID();
  const message = chatResponse?.choices?.[0]?.message;
  const text = typeof message?.content === "string" ? message.content : "";
  const output: Array<any> = [];

  if (text) {
    output.push({
      type: "message",
      id: `msg_${responseId}`,
      role: "assistant",
      content: [{ type: "output_text", text }]
    });
  }

  if (Array.isArray(message?.tool_calls)) {
    for (const tc of message.tool_calls) {
      output.push({
        type: "function_call",
        id: tc.id || `call_${crypto.randomUUID()}`,
        call_id: tc.id || `call_${crypto.randomUUID()}`,
        name: tc.function?.name || "",
        arguments: tc.function?.arguments || ""
      });
    }
  }

  return {
    id: `resp_${responseId}`,
    object: "response",
    created_at: chatResponse?.created ?? Math.floor(Date.now() / 1000),
    model: chatResponse?.model ?? "kira-mini-1.0",
    output,
    usage: chatResponse?.usage
      ? {
          input_tokens: chatResponse.usage.prompt_tokens ?? 0,
          output_tokens: chatResponse.usage.completion_tokens ?? 0,
          total_tokens: chatResponse.usage.total_tokens ?? 0
        }
      : null
  };
}

export function createSseEvent(event: string, data: unknown): string {
  return `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
}